name: Deploy caarzy api Laravel Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2 Instance
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /var/www/html/caarzy-api
          git fetch origin main
          git reset --hard origin/main
          
          php artisan migrate --force
          php artisan optimize:clear
          php artisan optimize

          sudo systemctl restart nginx
        EOF
